// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyhtpouazyhgxjxvhiny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95aHRwb3VhenloZ3hqeHZoaW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjg2OTcsImV4cCI6MjA2Mzg0NDY5N30.Irhn8MpvCkxuA8xlh5xwilaE8ZbOEiPhqnRRsicDVOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);